// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package database

import (
	"context"
)

type Querier interface {
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateCountry(ctx context.Context, arg CreateCountryParams) (Country, error)
	CreateMerchant(ctx context.Context, arg CreateMerchantParams) (Merchant, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCategory(ctx context.Context, id int64) error
	DeleteCountry(ctx context.Context, code string) error
	DeleteMerchant(ctx context.Context, id int64) error
	DeleteOrder(ctx context.Context, id int64) error
	DeleteOrderItem(ctx context.Context, orderID int64) error
	DeleteProduct(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetCategory(ctx context.Context, id int64) (Category, error)
	GetCountry(ctx context.Context, code string) (Country, error)
	GetMerchant(ctx context.Context, id int64) (Merchant, error)
	GetOrder(ctx context.Context, id int64) (Order, error)
	GetOrderItem(ctx context.Context, orderID int64) (OrderItem, error)
	GetProduct(ctx context.Context, id int64) (Product, error)
	GetUser(ctx context.Context, id int64) (User, error)
	ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error)
	ListCountries(ctx context.Context, arg ListCountriesParams) ([]Country, error)
	ListMerchants(ctx context.Context, arg ListMerchantsParams) ([]Merchant, error)
	ListOrderItems(ctx context.Context, arg ListOrderItemsParams) ([]OrderItem, error)
	ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error
	UpdateCountry(ctx context.Context, arg UpdateCountryParams) error
	UpdateMerchant(ctx context.Context, arg UpdateMerchantParams) error
	UpdateOrder(ctx context.Context, arg UpdateOrderParams) error
	UpdateOrderItem(ctx context.Context, arg UpdateOrderItemParams) error
	UpdateProduct(ctx context.Context, arg UpdateProductParams) error
	UpdateUsers(ctx context.Context, arg UpdateUsersParams) error
}

var _ Querier = (*Queries)(nil)
